AllCops:
    TargetRubyVersion: 3.2
    NewCops: enable

Metrics/AbcSize:
    Max: 27
# --------------------------
# CONFIGURACIONES GLOBALES 
#         INICIO
# --------------------------
Layout/IndentationWidth:
    Enabled: true
    Width: 4

Style/StringLiterals:
    EnforcedStyle: double_quotes

Style/Documentation:
    Enabled: false

Style/ClassAndModuleChildren:
    Enabled: false

# Style/BracesAroundHashParameters:
#     Enabled: false

# Style/SpaceInsideBrackets:
#     Enabled: false

Layout/SpaceInsideParens:
    Enabled: false

# permite tener espacio antes de la coma
Layout/SpaceBeforeComma:
    Enabled: false

Style/WordArray:
    Enabled: false
    EnforcedStyle: brackets

Style/RegexpLiteral:
    Enabled: false

Style/EmptyMethod:
    EnforcedStyle: expanded

Layout/SpaceInsideStringInterpolation:
    EnforcedStyle: space

Style/StringLiteralsInInterpolation:
    EnforcedStyle: double_quotes

Style/SymbolArray:
    EnforcedStyle: brackets

Layout/AccessModifierIndentation:
    Enabled: false

# Layout/IndentationConsistency:
#     EnforcedStyle: rails

Style/AsciiComments:
    Enabled: false
# --------------------------
#         FIN
# CONFIGURACIONES GLOBALES 
# --------------------------
#
# Metrics/LineLength:
#     Max: 195
#     Exclude:
#         - "test/*/*"
# 
Metrics/BlockLength:
    Max: 40
#     Exclude:
#         - "test/*/*"
# 
Metrics/ClassLength:
    Exclude:
        - "test/*/*"
    Max: 300
# 
# Style/ClassAndModuleChildren:
#     EnforcedStyle: compact
# 
Metrics/MethodLength:
    Max: 40