inherit_from: .rubocop_todo.yml

plugins:
    - rubocop-minitest
    - rubocop-rake

AllCops:
    NewCops: enable
    TargetRubyVersion: 3.2

Style/StringLiterals:
    EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
    EnforcedStyle: double_quotes

Layout/IndentationWidth:
    Width: 4

Layout/SpaceInsideStringInterpolation:
    EnforcedStyle: space